### ISSUE TITLE
Identity.Whoami returns nil Account struct

### ISSUE THREAD

**Issue by drlogout** [aetrion/dnsimple-go#24]
Identity.Whoami returns nil Account struct:

```go
whoami, err := client.Identity.Whoami()
if err != nil {
	log.Fatal(err)
}
fmt.Println(whoami.Data.Account) // <nil>
```

**Comment by weppos** [comment]
How are you authenticating? Are you using an Oauth token or other authentication mechanisms?

**Comment by drlogout** [comment]
with Oauth token
```go
client := dnsimple.NewClient(dnsimple.NewOauthTokenCredentials(oauthToken))
```

**Comment by weppos** [comment]
How did you generate the token? Is it generated as:

- Oauth token via Oauth dance
- User access token
- Account access token

**Comment by drlogout** [comment]
Account access token

**Comment by weppos** [comment]
This is very strange. Can you please provide the HTTP result of a curl request? Please remove specific IDs or credentials.

**Comment by weppos** [comment]
@drlogout any update?

**Comment by weppos** [comment]
Closing as can't reproduce. @drlogout please feel free to reopen when you can provide the requested info.
